---
# tasks file for web-server
  - name: install apache2
    apt:
     name: "{{ apachePackageName }}"
     update_cache: yes
     state: latest
 
  - name: enabled mod_rewrite
    apache2_module:
      name: rewrite
      state: present
    notify:
      - restart apache2
 
  - name: Copy index page
    copy:
      src: "{{ webContent }}"
      dest: "{{ wwwPath }}"

  - name: Update apache configuration
    template:
      src: port.j2
      dest: /etc/apache2/ports.conf
    notify:
      - restart apache2

